[tool.poetry]
name = "feathero"
version = "2025.11.01"
description = "Search using a genetic algorithm with machine learning the bes features to predict a target variable."
authors = ["Juan Carlos Moreno Sanchez <carlos.moreno.phd@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/phen4/feathero" 
repository = "https://gitlab.com/phen4/feathero"
keywords = ["feature selection", "predict"]
packages = [{include = "feathero", from = "."}]

[tool.poetry.dependencies]
python = "^3.12"

pandas = "^2.2.0"
numbers-parser = "^4.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
